
skillMetadata:
  sections:
    - name: Connection
      fields:
        - name: host
          type: text
          label: EIBNet/IP proxy adress or ip number
          value: "192.168.2.70"
        - name: portnum
          type: number
          label: Port number
          value: 3671
    - name: Entities
      fields:
        - name: light
          type: text
          label: YAML config for lights
          value: |
            {
            "essen": "1/2/3",
            "kueche": {
              "decke|default": "1/2/1",
              "hof": "5/2/6",
              "spot": "1/2/14",
              "terasse": "5/2/5",
            },
            "wohnzimmer": "1/2/2"
            }
        - name: blind
          type: text
          label: YAML config for blinds
          value: |
            {
            "essen": {
              "gross": "1/3/60",
              "klein": "1/3/61"
            },
            "kueche": {
              "fenster": "1/3/64",
              "tuer": "1/3/63"
            },
            "terasse": {
              "links": "1/3/57",
              "rechts": "1/3/59",
              "tuer": "1/3/58"
            }
            }
        - name: plug
          type: text
          label: YAML config for plugs
          value: |
            {
            "essen": "1/1/8",
            "kueche": "1/1/9"
            }
        - name: special
          type: text
          label: YAML config for special objects
          value: |
            {
            "brunnen": "5/1/3"
            }    
    - name: Command
      fields:
        - name: actions
          type: text
          label: YAML config for actions
          value: |
            {
            "aktiviere": "1",
            "deaktiviere": "0",
            " halb": "128|num",
            " hoch": "0|num",
            " rauf": "0|num",
            " auf": "0|num",
            " raus": "0|num",
            " rein": "255|num",
            " runter": "255|num",
            " zu": "255|num",
            " an": "1",
            " ein": "1",
            " aus": "0"
            }
