
skillMetadata:
  sections:
    - name: Connection
      fields:
        - name: host
          type: text
          label: EIBNet/IP proxy adress or ip number
          value: "192.168.2.70"
        - name: portnum
          type: number
          label: Port number
          value: 3671
    - name: Entities
      fields:
        - name: light
          type: text
          label: YAML config for lights
          value: |
            {
            "essen": "1/2/3",
            "kueche": {
              "decke": "1/2/1",
              "hof": "5/2/6",
              "spot": "1/2/14",
              "terasse": "5/2/5",
              "default": "1/2/1"
            },
            "wohnzimmer": "1/2/2"
            }
        - name: blind
          type: text
          label: YAML config for blinds
          value: |
            {
            "essen": {
              "gross": "1/3/60",
              "klein": "1/3/61"
            },
            "kueche": {
              "fenster": "1/3/64",
              "tuer": "1/3/63"
            },
            "terasse": {
              "links": "1/3/57",
              "rechts": "1/3/59",
              "tuer": "1/3/58"
            }
            }
        - name: plug
          type: text
          label: YAML config for plugs
          value: |
            {
            "essen": "1/1/8",
            "kueche": "1/1/9"
            }          
    - name: Command
      fields:
        - name: actions
          type: text
          label: YAML config for actions
          value: |
            {
            "aktiviere": 1,
            "deaktiviere": 0,
            " an": 1,
            " ein": 1,
            " auf": 0,
            " aus": 0,
            " halb": 128,
            " hoch": 0,
            " rauf": 255,
            " raus": 0,
            " rein": 255,
            " runter": 255,
            " zu": 255
            }
