{
    "essen|esstisch|esszimmer": {
        "gross": "1/3/60",
        "klein": "1/3/61"
    },
    "küche|kochen": {
        "fenster": "1/3/64",
        "tür": "1/3/63"
    },
    "terrasse": {
        "links|linke": "1/3/57",
        "rechts|rechte": "1/3/59",
        "tür|default": "1/3/58"
    },
    "wohnzimmer|wohnen": {
        "klein": "1/3/55",
        "groß": "1/3/56"
    },
    "ankleide": "1/3/65",
    "wirtschaft": "1/3/54",
    "bad": {
        "unteres|unten|default": {
            "klo|wc|osten": "1/3/52",
            "dusche|default": "1/3/53"
        },
        "oberes|oben": "2/3/24"
    },
    "schalfzimmer": "1/3/51",
    "flur|gang|carport": "1/3/50",
    "wc|klo": "1/3/62",
    "florian": "2/3/22",
    "johannes": "2/3/31",
    "büro|spielzimmer|spielen": {
        "tür": "2/3/28",
        "fenster": "2/3/26"
    },
    "balkontür": "2/3/28",
    "gäste": "2/3/30"
}
